# NumPy Ćwiczenia

#### Import NumPy jako np

In [1]:
import numpy as np

# Zadanie 1
#### Utwórz tablicę 10 zer

Rezultat:

```
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```






In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Zadanie 2
#### Utwórz tablicę 10 jedynek

Rezultat:

```
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```



In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Zadanie 3
#### Utwórz tablicę 10 piątek


Rezultat:
```
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
```



In [20]:
a = np.ones(10) * 5

a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Zadanie 4
#### Utwórz następującą macierz:

```
array([[ 1.01,  1.02,  1.03,  1.04,  1.05,  1.06,  1.07,  1.08,  1.09,  1.10],
       [ 1.11,  1.12,  1.13,  1.14,  1.15,  1.16,  1.17,  1.18,  1.19,  1.20],
       [ 1.21,  1.22,  1.23,  1.24,  1.25,  1.26,  1.27,  1.28,  1.29,  1.30],
       [ 1.31,  1.32,  1.33,  1.34,  1.35,  1.36,  1.37,  1.38,  1.39,  1.40],
       [ 1.41,  1.42,  1.43,  1.44,  1.45,  1.46,  1.47,  1.48,  1.49,  1.50],
       [ 1.51,  1.52,  1.53,  1.54,  1.55,  1.56,  1.57,  1.58,  1.59,  1.60],
       [ 1.61,  1.62,  1.63,  1.64,  1.65,  1.66,  1.67,  1.68,  1.69,  1.70],
       [ 1.71,  1.72,  1.73,  1.74,  1.75,  1.76,  1.77,  1.78,  1.79,  1.80],
       [ 1.81,  1.82,  1.83,  1.84,  1.85,  1.86,  1.87,  1.88,  1.89,  1.90],
       [ 1.91,  1.92,  1.93,  1.94,  1.95,  1.96,  1.97,  1.98,  1.99,  2.00]])
```


In [7]:
np.linspace(1, 2, 100).reshape(10, 10)

array([[1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909],
       [1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919],
       [1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929],
       [1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939],
       [1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949],
       [1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ],
       [1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ],
       [1.70707071, 1.71717172, 1.7272727

# Zadanie 5
Utwórz tablicę 36 równomiernie rozmieszczonych punktów między 0 a 1, a następnie przekształć ją w macierz 6 × 6.

Następnie:
- Zwróć trzeci wiersz tej macierzy
- Zwróć ostatnią kolumnę
- Zwróć środkowy fragment macierzy 3 × 3





In [6]:
punkty = np.linspace(0, 1, 36)
macierz = punkty.reshape(6, 6)

trzeci_wiersz = macierz[2, :]
ostatnia_kolumna = macierz[:, -1]
srodkowy_fragment_3x3 = macierz[1:4, 1:4]

macierz, trzeci_wiersz, ostatnia_kolumna, srodkowy_fragment_3x3

(array([[0.        , 0.02857143, 0.05714286, 0.08571429, 0.11428571,
         0.14285714],
        [0.17142857, 0.2       , 0.22857143, 0.25714286, 0.28571429,
         0.31428571],
        [0.34285714, 0.37142857, 0.4       , 0.42857143, 0.45714286,
         0.48571429],
        [0.51428571, 0.54285714, 0.57142857, 0.6       , 0.62857143,
         0.65714286],
        [0.68571429, 0.71428571, 0.74285714, 0.77142857, 0.8       ,
         0.82857143],
        [0.85714286, 0.88571429, 0.91428571, 0.94285714, 0.97142857,
         1.        ]]),
 array([0.34285714, 0.37142857, 0.4       , 0.42857143, 0.45714286,
        0.48571429]),
 array([0.14285714, 0.31428571, 0.48571429, 0.65714286, 0.82857143,
        1.        ]),
 array([[0.2       , 0.22857143, 0.25714286],
        [0.37142857, 0.4       , 0.42857143],
        [0.54285714, 0.57142857, 0.6       ]]))

# Zadanie 6
Stwórz numpy array z wartościami od 1 do do 9, wyświetl go, a następnie odwróć tę tablicę (pierwszy element zostaje ostatnim, itd.).

In [8]:
np.arange(1, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

# Zadanie 7
Stwórz następujący numpy array: `[1, 23, 4, 31, 1, 1, 4, 23, 4, 1]`, a następnie wypisz wszystkie unikalne (nie powtarzające się) elementy.

In [10]:
np.unique(np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1]))

array([ 1,  4, 23, 31])

# Zadanie 8
Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10.

In [11]:
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Zadanie 9
Spośród tablicy wartości: `[23, 45, 112, 150, 43, 254, 95, 8]` wyfiltruj te, które są większe od 100.

In [12]:
a = np.array([23, 45, 112, 150, 43, 254, 95, 8])

a[a > 100]

array([112, 150, 254])

# Zadania 10
Stwórz poniższą macierz 4x4, a następnie:


$ \begin{bmatrix}
1 & 15 & 4 & 13 \\
8 & 21 & 3 & 12 \\
11 & 13 & 11 & 5 \\
32 & 13 & 0 & 2
\end{bmatrix}  $


- wyświetl element z drugiego wiersza i trzeciej kolumny,
- oblicz jej wyznacznik wykorzystując odpowiednią funkcję z biblioteki NumPy; **wskazówka:** użyj funkcji `np.linalg.det()`
- sumę elementów na głównej przekątnej,
- znajdź element największy i najmniejszy

In [13]:
macierz_4x4 = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

element_2_3 = macierz_4x4[1, 2]
wyznacznik = np.linalg.det(macierz_4x4)
suma_przekatnej = np.trace(macierz_4x4)
maksimum = np.max(macierz_4x4)
minimum = np.min(macierz_4x4)

element_2_3, wyznacznik, suma_przekatnej, maksimum, minimum

(np.int64(3),
 np.float64(-19963.99999999999),
 np.int64(35),
 np.int64(32),
 np.int64(0))

# Zadanie 11
Stwórz dowolną tablicę wartości, a następnie oblicz średnią i medianę.

In [15]:
a = np.arange(10, 50)

np.median(a), np.mean(a)

(np.float64(29.5), np.float64(29.5))

# Zadanie 12
Stwórz dowolną tablicę wartości, a następnie je znormalizuj - tj. od każdego elementu tablicy odejmij średnią i podziel przez odchylenie standardowe.

In [16]:
a = np.array([23, 45, 112, 150, 43, 254, 95, 8])

a = (a - np.mean(a)) / np.std(a)

a

array([-0.8957852 , -0.60703393,  0.27234495,  0.77109715, -0.63328404,
        2.13610316,  0.04921897, -1.09266107])

# Zadanie 13
Stwórz funkcję, która przyjmuje dwa wektory (oba o tym samym wymiarze) w postaci numpy tablicy, a zwróci odległość euklidesową między nimi.

 $ d\left( p,q\right)   = \sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $

In [18]:
def fun(a, b):
    return np.sqrt(np.sum((b - a) ** 2))


fun(np.array([1, 2, 3]), np.array([4, 5, 6]))

np.float64(5.196152422706632)